### ISSUE TITLE
iot broker issue with connecting to iot discovery

### ISSUE THREAD

**Issue by mohamedamin10010027** [Aeronbroker/Aeron#19]
when i send queryContext request that request is sent to iot discovery but the response is  the following
{"errorCode":{"code":404,"reasonPhrase":"CONTEXT ELEMENT NOT FOUND","details":"Discovery response: RECEIVER INTERNAL ERROR (details: Receiver response empty)"},"contextResponses":[]}

when i checked iot discovery i found that iot broker appended "//ngsi9/DiscoverAvailabillity "  to the url request to iot discovery ..i put in the config.default file in the uri of ngsi9 the ip of iot discovery http://130.206.177.25:8080/ ?

**Comment by flaviocirillo** [comment]
The IoT Broker contacts the IoT Discovery address specified in the iotbroker.conf.local and in case it is not found there, as backup it reads from the iotbroker.conf.default (see [IoT Broker system configuration](https://github.com/Aeronbroker/Aeron/blob/master/doc/compilationandconfiguration.md#iot-broker-system-configuration)). 

The parameter to set is _iotbroker_ngsi9uri_ (see the [default configuration file](https://github.com/Aeronbroker/Aeron/blob/master/IoTBroker-runner/iotbroker.conf.default)). 

From that address, the IoT Broker appends /ngsi9/discoveryContextAvailability as defined in the [Open NGSI-9 RESTful API specification by FIWARE](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_NGSI-9_Open_RESTful_API_Specification_(PRELIMINARY)).

**Comment by mohamedamin10010027** [comment]
thank you for response 
i have already done that but the server logs is
osgi> 2018-02-16 12:12:04 INFO  RestProviderController:409 - 

 <--- NGSI-10 has received request for Context query resource ---> 

2018-02-16 12:12:04 INFO  RestProviderController:349 - Impossible to get the Json Request! Please check the error using debug mode.
2018-02-16 12:12:04 WARN  Southbound:819 - Response from remote server empty
2018-02-16 12:12:04 INFO  IotBrokerCore:749 - 0 query Services found

and the same response when i queryContext 
and the query is 
curl http://130.206.121.137:8060/ngsi10/queryContext  -s -S --header 'Content-Type: application/json'  --header 'Accept: application/json'  -d @- <<EOF
{
    "entities": [{
        "isPattern": false,
        "id": "sensor6"
       
    }]
}
EOF 

and that in the file iotbroker.cofig.local

#!/bin/bash
iotbroker_dirconfig='/home/ubuntu/Aeron/fiwareRelease'
iotbroker_bundlesconfigurationlocation='/home/ubuntu/Aeron/fiwareRelease/bundleC$
iotbroker_hsqldbdirectory='//home//ubuntu//Aeron//SQL_database//database//linkDB'
iotbroker_logfile='/home/ubuntu/Aeron/IoTBroker-runner/logs/iotbroker.log'
iotbroker_ngsi9uri='http://130.206.121.87.8080'

iot discovery hears that query in its logs and appear in that lot discovery logs "URL: http://130.206.121.22:8080//ngsi9/discoverContextAvailability"
so what is the problem?

**Comment by flaviocirillo** [comment]
Dear Mohamed,

I suspect a bad behaviour with the OSGi enviroment of the IoT Discovery.

Please follow the new compilation instructions here : https://github.com/Aeronbroker/NEConfMan#compilation-procedure

and then run it following the configuration instructions here: https://github.com/Aeronbroker/NEConfMan#configure-the-nec-confman-with-setup-scripts
If the problem persists, please send me the output of the "ss" command (check the end of the https://github.com/Aeronbroker/NEConfMan#configure-the-nec-confman-with-setup-scripts section), and the ConfMan_Runner/confman.conf.default, ConfMan_Runner/confman.conf.local and ConfMan_Runner/confman/configuration/config.ini

Thank you
Best Regards
Flavio

**Comment by mohamedamin10010027** [comment]
thank you MR Flavio ,
your are right the problem was in IoT Discovery that i installed before .
 i have installed ConfMan IoT Discovery,  it works well and my problem is solved
