### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by IAIS4EP** [Aeronbroker/Aeron#5]
Dear IoT Broker team,

at our Accelerator EUROPEANPIONEERS, we have tested some Enablers, also IoT Broker.

One of our results is a IoT demo scenario for this component.

Do you think this could be a useful contribution to the project, allowing new developers very easy visual access to Enabler features, with 1 minute setup?

Please have a look:

https://github.com/IAIS4EP/fiware/tree/master/ge/ge_iotbroker 

If you like it - can we make it to a pull request?

kind regards
Peter

**Comment by flaviocirillo** [comment]
Dear Peter,

thank you very much for your contribution. Your scenarios would be very useful for users which are approaching for the first time the FIWARE project and in particular the IoT Broker.

So please, go ahead for the pull request. I have created a folder where, from now on, we will put our testing scenarios (iotplatform.iotbroker.testingscenarios/). 
So please create your own folder there and describe your scripts in the README.md within such folder.

Looking forward to your pull request.

Best Regards
Flavio

**Comment by 1605200517** [comment]
Hi, Flavio,

our project has ended, but I still would like to share the codes. While I am not sure how to make a pull request between different folders in different projects, maybe you could guide me via Skype or just copy over the sources?

thx 
Peter

**Comment by Aeronbroker** [comment]
Hi Peter,

as far as I remember you wanted to add some testing scenarios to the Aeron Broker, you can create your folder in this folder: iotplatform.iotbroker.testingscenarios/
Please follow this well done GitHub guide for Pull Requests https://help.github.com/articles/creating-a-pull-request/
Best Regards
Flavio

**Comment by 1605200517** [comment]
Dear Flavio, I sent the pull request.
